from __future__ import annotations

import json
from pathlib import Path

import gradio as gr
import pandas as pd

ROOT = Path(__file__).resolve().parent
DATASET_URL = "https://huggingface.co/datasets/kugguk/lottobench-community-benchmark"
SOURCE_URL = "https://github.com/kugguk2022/lotteries-init-at-your-service"

results = pd.read_csv(ROOT / "data" / "benchmark_results.csv")
poi_results = pd.read_csv(ROOT / "data" / "poi_g_subset_results.csv")
manifest = json.loads((ROOT / "data" / "benchmark_manifest.json").read_text(encoding="utf-8"))

PROVIDER_LABELS = {
    "provider": "Provider",
    "pair_coverage": "Pair coverage (primary)",
    "number_coverage": "Number coverage",
    "mean_jaccard_diversity": "Diversity",
    "unpopularity_lift": "Unpopularity lift",
    "expected_roi_per_ticket": "Modelled ROI/ticket",
    "hit_recall": "Hit recall",
}

provider_view = (
    results[list(PROVIDER_LABELS)]
    .sort_values("pair_coverage", ascending=False)
    .round(4)
    .rename(columns=PROVIDER_LABELS)
)


def _hits(rate_column: str, count_column: str) -> pd.Series:
    return poi_results.apply(
        lambda row: f"{int(row[count_column])} / {int(row['holdout'])} ({row[rate_column]:.2%})",
        axis=1,
    )


# Containment is reported on both axes against their own denominators. Collapsing to the
# full-ticket figure alone understates a main-pool reducer whenever star entropy is low.
poi_view = poi_results.assign(
    shortlist=poi_results["subset_size"].map("{:,}".format),
    distinct_mains=poi_results["mean_distinct_main_sets"].round(1),
    main_hits=_hits("containment_rate_main", "contained_draws_main"),
    main_base=poi_results["random_expected_containment_rate_main"].map("{:.2%}".format),
    main_lift=poi_results["containment_lift_main"].round(2),
    full_hits=_hits("containment_rate_full", "contained_draws_full"),
    full_base=poi_results["random_expected_containment_rate_full"].map("{:.2%}".format),
    full_lift=poi_results["containment_lift_full"].round(2),
    star_entropy=poi_results["star_share_entropy"].round(2),
    roi=poi_results["modeled_expected_roi_per_selected_ticket"].round(4),
)[
    [
        "shortlist",
        "distinct_mains",
        "main_hits",
        "main_base",
        "main_lift",
        "full_hits",
        "full_base",
        "full_lift",
        "star_entropy",
        "roi",
    ]
].rename(
    columns={
        "shortlist": "Shortlist",
        "distinct_mains": "Distinct main sets",
        "main_hits": "Main contained",
        "main_base": "Main baseline",
        "main_lift": "Main lift (primary)",
        "full_hits": "Full contained",
        "full_base": "Full baseline",
        "full_lift": "Full lift",
        "star_entropy": "Star entropy",
        "roi": "Modelled ROI (top 5)",
    }
)

game = manifest["game"]
poi_eval = manifest["poi_g_evaluation"]
best = provider_view.iloc[0]
singles = provider_view[provider_view["Provider"] != "coordinated_aggregation"]
best_single = singles.iloc[0]
# Stated as a comparison only when aggregation actually won; a losing run must not read as a win.
aggregation_leads = best["Provider"] == "coordinated_aggregation"
null_hit_recall = game["main_k"] / game["main_n"]
worst_star_entropy = poi_results["star_share_entropy"].min()
worst_min_star = poi_results["min_star_share"].min()

if aggregation_leads:
    headline = (
        f"Coordinated aggregation leads at **{best['Pair coverage (primary)']:.4f}** against "
        f"**{best_single['Pair coverage (primary)']:.4f}** for the best single provider "
        f"(`{best_single['Provider']}`) — a "
        f"{best['Pair coverage (primary)'] / best_single['Pair coverage (primary)'] - 1:+.1%} "
        "difference at identical budget. That is the claim under test: recombining already-proposed "
        "tickets reaches more of the combinatorial space than any one contributor spending the same "
        f"{manifest['evaluation']['budget']} tickets."
    )
else:
    headline = (
        f"`{best['Provider']}` leads at **{best['Pair coverage (primary)']:.4f}**, ahead of "
        "coordinated aggregation. On this run, recombining proposals did not beat the best single "
        "provider at equal budget — the claim under test is not supported here."
    )

header = f"""
# LottoBench Community Leaderboard

Forward-only, equal-budget results on deterministic synthetic data. Every figure below is read from
a frozen, seeded run — this Space computes nothing at request time.

**Benchmark** `{manifest['benchmark_version']}` · **LottoBench** `{manifest['lottobench_version']}` ·
**seed** `{manifest['seed']}` · **snapshot** `{manifest['dataset_sha256'][:16]}…`

[Dataset]({DATASET_URL}) · [Source]({SOURCE_URL})
"""

calibration_warning = """
> **What this data can and cannot settle.** The draw history is generated by a uniform random
> number generator, so it contains no co-occurrence structure to find. No method can exceed
> containment lift 1.0 on it, in expectation. Lifts near 1.0 below confirm the harness is
> calibrated — they are **not** evidence for or against any method on real draws. A claim about
> real draws needs a non-uniform or real-data track, which this benchmark does not yet have.
"""

provider_note = f"""
## Provider track

Four strategies, {manifest['evaluation']['budget']} tickets per draw, scored on
{manifest['evaluation']['holdout']} draws of a {game['main_k']}-of-{game['main_n']} pool plus a
{game['auxiliary_k']}-of-{game['auxiliary_n']} auxiliary pool.

Primary metric is **pair coverage**. {headline}

Hit recall is a secondary metric and sits on the null: every provider lands near the fair-draw
expectation of {game['main_k']}/{game['main_n']} = {null_hit_recall:.4f}. Modelled ROI is negative
for every row and always will be — a fair lottery is negative-sum.
"""

poi_note = f"""
## POI-G candidate subsets

POI-G is a search-space reducer, not a five-ticket strategy. Containment is scored on the entire
shortlist over {poi_eval['holdout']} draws; modelled ROI is scored only on the five top-ranked
tickets, because those are the only ones anyone would buy.

**Containment is reported on two axes, against two different denominators.** POI-G ranks by pair
co-occurrence, which is dominated by the main pool, and ties in the integer score are broken by
enumeration order. Small shortlists are therefore close to auxiliary-degenerate — at the smallest
size the least-represented star takes {worst_min_star:.1%} of slots against a uniform 25%, and star
entropy falls to {worst_star_entropy:.2f}. Scoring only the full ticket charges the reducer for an
axis it barely ranks on, so **main-only containment against the main-only universe is the primary
metric** and the full-ticket figure is reported beside it.
"""

glossary = """
| Metric | Meaning |
|---|---|
| **Pair coverage** | Fraction of all number pairs covered by at least one ticket in the portfolio. Primary provider metric. |
| **Number coverage** | Fraction of the main number pool touched by the portfolio. |
| **Diversity** | 1 − mean pairwise Jaccard similarity between tickets. 1 means fully disjoint. |
| **Unpopularity lift** | Portfolio expected payout ÷ that of an equally sized uniformly popular portfolio. Above 1 leans unpopular, which raises conditional payout by reducing jackpot sharing. |
| **Modelled ROI/ticket** | Jackpot-tier `E[payout] · P(win) / price − 1`. A comparative diagnostic from a single-tier model, not a payout forecast, and not realised returns. |
| **Hit recall** | Mean fraction of a ticket's numbers appearing in the actual draw. Fair-draw expectation is `main_k / main_n`. |
| **Distinct main sets** | How many distinct main combinations the shortlist actually held. At small sizes this is nearly the whole shortlist, which is what makes it a main-combination shortlist. |
| **Main lift** | Main-combination containment ÷ `distinct main sets / C(main_n, main_k)`. Does the reducer find the right numbers? |
| **Full lift** | Whole-ticket containment ÷ `subset_size / universe`. Would you actually hold the winning ticket? |
| **Star entropy** | How evenly shortlist slots spread over the auxiliary pool. 1.0 = uniform. Low values mean the full-ticket column understates the reducer. |
"""

protocol = f"""
- **Forward-only** — at each holdout step every provider and shortlist is fitted on strictly earlier
  rows, so there is no leakage path.
- **Equal budget** — {manifest['evaluation']['budget']} tickets per provider per draw; coverage
  comparisons are meaningless otherwise.
- **Holdouts** — {manifest['evaluation']['holdout']} draws for the provider track,
  {poi_eval['holdout']} for POI-G containment. Containment is a rare binary event and needs the
  longer window.
- **Frozen game** — `main_n={game['main_n']}, main_k={game['main_k']},
  auxiliary_n={game['auxiliary_n']}, auxiliary_k={game['auxiliary_k']}` →
  {poi_results['universe_size'].iloc[0]:,} legal tickets over
  {poi_results['main_universe_size'].iloc[0]:,} main combinations.
- **Deterministic** — seed `{manifest['seed']}`; the aggregator is a greedy submodular selection,
  identical given identical inputs.
- **Snapshot** — `{manifest['dataset_sha256']}`. Results are comparable only when this digest,
  the provider set, budget, holdout, seed, and scoring code all match.

```bash
python scripts/build_platform_bundles.py
```
"""

disclaimer = """
---

Synthetic software benchmark only. These results are not evidence that a fair lottery is
predictable, are not performance on any operated lottery, and are not financial or gambling advice.
LottoBench places no wagers and does not improve mechanical odds. The safest financial baseline is
not to play. If gambling is causing harm, contact a local support service such as
[BeGambleAware](https://www.begambleaware.org/).
"""

with gr.Blocks(title="LottoBench Community Leaderboard") as demo:
    gr.Markdown(header)
    gr.Markdown(calibration_warning)
    gr.Markdown(provider_note)
    gr.Dataframe(provider_view, interactive=False, wrap=True)
    gr.Markdown(poi_note)
    gr.Dataframe(poi_view, interactive=False, wrap=True)
    with gr.Accordion("Metric definitions", open=False):
        gr.Markdown(glossary)
    with gr.Accordion("Protocol and reproduction", open=False):
        gr.Markdown(protocol)
    gr.Markdown(disclaimer)

if __name__ == "__main__":
    demo.launch()
